### ISSUE TITLE
Additional Acme-provider:  dns-nsupdate (DNS01 with CNAME delegated auth)

### ISSUE THREAD

**Issue by swordfish90s** [Djelibeybi/homeassistant-acme.sh-addon#3]
Hi Avi,

Would you be able to add an additional Acme-provider:  dns-nsupdate

Specifically so I can use the DNS01 method with the CNAME auth delegation.

I use acme.sh on other projects and use the dns-nsupdate provider.
My standard process is as follows:

    export NSUPDATE_SERVER="dns-server.myothermydomain.com.au"
    export NSUPDATE_KEY="path-to/ddns_key.conf"
    export NSUPDATE_ZONE="ddns.myotherdomain.com.au"

    acme.sh --set-default-ca --server letsencrypt

    add a DNS Setting:
    _acme-challenge.ha.mydomain.com.au CNAME _acme-challenge.ddns.myotherdomain.com.au.

    acme.sh --issue --dns dns_nsupdate -d ha.mydomain.com.au --challenge-alias ddns.myotherdomain.com.au
    acme.sh --install-cert  .....

Then the usual renew daily.

With this method I can use the same DDNS domain with CNAMEs to authenticate all my SSL certs.

Thanks,
Rob

**Comment by Djelibeybi** [comment]
I don't remove any DNS providers, so that's already taken care of. What I do need to do is allow you to specify the `--challenge-alias` which is not currently possible.

**Comment by Djelibeybi** [comment]
This should now be available via the new acme.sh (beta) addon. I don't use this option, so please test the beta and let me know if it works.

**Comment by swordfish90s** [comment]
> I don't remove any DNS providers, so that's already taken care of. What I do need to do is allow you to specify the `--challenge-alias` which is not currently possible.

Ok, that's great - only your documentation lists a specific set of providers, and without something like "supports any provider acme.sh does", then I believed it was less.

**Comment by Djelibeybi** [comment]
> Ok, that's great - only your documentation lists a specific set of providers, and without something like "supports any provider acme.sh does", then I believed it was less.

I certainly intended to write that, but it seems some of the words went missing. 😂

**Comment by swordfish90s** [comment]
in acme-sh_beta/config.yaml

the bit below looks a lot like a defined list that does not include dns_nsupdate
```
schema:   
     acmeprovider: list(letsencrypt|letsencrypt_test|buypass|buypass_test|zerossl|sslcom|google|googletest)
```
That would be why I thought it be a subset of those provided by acme.sh

Rob

**Comment by Djelibeybi** [comment]
Those are ACME providers not DNS providers. You would pick `letsencrypt` from that list, given the details from your initial message.

Set `dnsprovider` to `dns_nsupdate`

**Comment by swordfish90s** [comment]
dolt! -  too many "providers" I got lost.

**Comment by swordfish90s** [comment]
tested Beta:

got log:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/issue-cert.sh
[21:45:21] INFO: Copying the default account.conf file
[21:45:21] INFO: Marking restart script executable.
[21:45:22] INFO: Registering account
[Tue Aug 27 21:45:23 AEST 2024] Account key creation OK.
[Tue Aug 27 21:45:23 AEST 2024] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Tue Aug 27 21:45:25 AEST 2024] Registered
[Tue Aug 27 21:45:25 AEST 2024] ACCOUNT_THUMBPRINT='ATEu-QT3vFRQL0Adyg3YcxMwEoMX1bdavTuZgIQCxtA'
[21:45:25] INFO: Setting default CA
[Tue Aug 27 21:45:25 AEST 2024] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
/etc/cont-init.d/issue-cert.sh: line 78: syntax error near unexpected token `||'
cont-init: info: /etc/cont-init.d/issue-cert.sh exited 2
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped```

Which doesn't look like a mis-config on my end.

**Comment by Djelibeybi** [comment]
Yeah, I missed adding a `\` to the new line. Give 2024.8.2 a whirl.

**Comment by swordfish90s** [comment]
looks great - I have a new cert.

**Comment by Djelibeybi** [comment]
Excellent. I'll close this for now and if anything breaks at renew time, let me know.

**Comment by swordfish90s** [comment]
Hi,

Renew time occurred, and all is well.  Cert updated, and Nginx restarted.

Candidate to progress from Beta.

Rob

**Comment by christianbur** [comment]
I have just successfully tested the dnschallengealias: function with the dns-plugin dns_nsupdate, thanks for your work.

**Comment by Djelibeybi** [comment]
I'm hoping to get some time this weekend or next to merge the changes into the GA version and release it.
